INSERT INTO ward VALUES (1,'nec metus');
INSERT INTO ward VALUES (2,'ac sem');
INSERT INTO ward VALUES (3,'lectus sit');
INSERT INTO ward VALUES (4,'lacus vestibulum');
INSERT INTO ward VALUES (5,'nec tempus');
INSERT INTO ward VALUES (6,'odio.');
INSERT INTO ward VALUES (7,'metus.');
INSERT INTO ward VALUES (8,'aliquam');
INSERT INTO ward VALUES (9,'velit. Cras');
INSERT INTO ward VALUES (10,'consequat');
INSERT INTO ward VALUES (11,'in consequat');
INSERT INTO ward VALUES (12,'purus, in');
INSERT INTO ward VALUES (13,'et magnis');
INSERT INTO ward VALUES (14,'sit');
INSERT INTO ward VALUES (15,'hendrerit id,');
INSERT INTO ward VALUES (16,'tincidunt aliquam');
INSERT INTO ward VALUES (17,'mollis.');
INSERT INTO ward VALUES (18,'tellus sem');
INSERT INTO ward VALUES (19,'faucibus leo,');
INSERT INTO ward VALUES (20,'sed');
INSERT INTO ward VALUES (21,'mollis');
INSERT INTO ward VALUES (22,'lorem semper');
INSERT INTO ward VALUES (23,'magna.');
INSERT INTO ward VALUES (24,'Vivamus');
INSERT INTO ward VALUES (25,'erat. Etiam');
INSERT INTO ward VALUES (26,'a neque.');
INSERT INTO ward VALUES (27,'sapien.');
INSERT INTO ward VALUES (28,'nisl. Nulla');
INSERT INTO ward VALUES (29,'semper et,');
INSERT INTO ward VALUES (30,'ac');
INSERT INTO ward VALUES (31,'consectetuer');
INSERT INTO ward VALUES (32,'Curae;');
INSERT INTO ward VALUES (33,'aliquet libero.');
INSERT INTO ward VALUES (34,'auctor,');
INSERT INTO ward VALUES (35,'Fusce');
INSERT INTO ward VALUES (36,'purus gravida');
INSERT INTO ward VALUES (37,'aliquet diam.');
INSERT INTO ward VALUES (38,'posuere, enim');
INSERT INTO ward VALUES (39,'pede, malesuada');
INSERT INTO ward VALUES (40,'at,');
INSERT INTO ward VALUES (41,'Duis');
INSERT INTO ward VALUES (42,'neque.');
INSERT INTO ward VALUES (43,'Curabitur');
INSERT INTO ward VALUES (44,'ridiculus');
INSERT INTO ward VALUES (45,'et ipsum');
INSERT INTO ward VALUES (46,'sem');
INSERT INTO ward VALUES (47,'mus.');
INSERT INTO ward VALUES (48,'tempus');
INSERT INTO ward VALUES (49,'blandit enim');
INSERT INTO ward VALUES (50,'Nam');
INSERT INTO ward VALUES (51,'Nullam vitae');
INSERT INTO ward VALUES (52,'augue ut');
INSERT INTO ward VALUES (53,'Duis');
INSERT INTO ward VALUES (54,'sit amet');
INSERT INTO ward VALUES (55,'ante');
INSERT INTO ward VALUES (56,'malesuada fames');
INSERT INTO ward VALUES (57,'eleifend egestas.');
INSERT INTO ward VALUES (58,'eget');
INSERT INTO ward VALUES (59,'non lorem');
INSERT INTO ward VALUES (60,'ac mattis');
INSERT INTO ward VALUES (61,'sodales. Mauris');
INSERT INTO ward VALUES (62,'sit amet');
INSERT INTO ward VALUES (63,'augue');
INSERT INTO ward VALUES (64,'luctus aliquet');
INSERT INTO ward VALUES (65,'sed,');
INSERT INTO ward VALUES (66,'parturient montes,');
INSERT INTO ward VALUES (67,'dolor. Quisque');
INSERT INTO ward VALUES (68,'adipiscing');
INSERT INTO ward VALUES (69,'justo. Proin');
INSERT INTO ward VALUES (70,'urna justo');
INSERT INTO ward VALUES (71,'Donec dignissim');
INSERT INTO ward VALUES (72,'malesuada');
INSERT INTO ward VALUES (73,'amet');
INSERT INTO ward VALUES (74,'iaculis aliquet');
INSERT INTO ward VALUES (75,'in, hendrerit');
INSERT INTO ward VALUES (76,'mauris');
INSERT INTO ward VALUES (77,'a sollicitudin');
INSERT INTO ward VALUES (78,'Vivamus non');
INSERT INTO ward VALUES (79,'Duis ac');
INSERT INTO ward VALUES (80,'Vivamus sit');

COMMIT;
